var iputils = require("./iputils");
var wait = new (require("./Wait"));

function generateDnsmasqConf(obj, filename, callback) {
    var config = [ "# This file was generated by "+process.argv[1]+" on "+new Date, '' ]; // will hold the dnsmasq.conf entries

    function addConfigLine(prefix, sub, domain, dst) {
      var host = (sub==""?domain:sub+"."+domain)+".bit";
      if (!iputils.isPlausibleDomain(host)) return;
      if (iputils.isIPv4Address(dst)) {
        if (iputils.isRoutableIPv4Address(dst)) {
          config.push(prefix+"/"+host+"/"+dst);
        }
      } else {
        iputils.lookupDomain(dst, wait.for(function(err,data) {
          if (!err) {
            addConfigLine(prefix, sub, domain, data);
          }
        }));
      }
    }

    // start with legacy parsing for now
    for (var name in obj) {
      var value = obj[name];
      if (value.map) {
        for (var key in value.map) {
          var item = value.map[key];
          if (typeof item == "string") {
            // should be an IP address
            addConfigLine("address=", key, name, item);
          } else if (item) {
            // probably an object. check for "ns" and "translate" fields.
            if (item.ns) {
              if (item.ns instanceof Array) {
                // multiple NS. great. I don't think dnsmasq can handle that.
                var ns = item.ns[~~(Math.random()*item.ns.length)];
                addConfigLine("server=",key, name, ns);
              } else if (typeof item.ns == "string") {
                // not sure if legit. accept for now. XXX
                addConfigLine("server=", key, name, item.ns);
              } else {
                // bogus ns field. ignore.
              }
            }
            if (item.translate) {
              // XXX not implemented. can dnsmasq do that?
            }
          } else {
            // invalid map field. probably "null" or somesuch nonsense. ignore.
          }
        }
      }
    }

    wait.on("done", function(){
      var data = config.join('\n');
      require("fs").writeFile(filename, data, 'utf8', callback);
    });
    wait.start();
}

module.exports = {
  generateDnsmasqConf: generateDnsmasqConf
};
